# Generated by Django 3.1.1 on 2021-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('rcnumber', models.CharField(max_length=50)),
                ('chasisnumber', models.CharField(max_length=20)),
                ('totalseating', models.CharField(max_length=100)),
            ],
        ),
    ]
